#!/bin/bash

iDIR="$HOME/.config/hypr/mako/icons"

SOURCE="alsa_input.pci-0000_00_1b.0.analog-stereo"

# Get Volume
get_volume() {
    volume=$(pamixer --source $SOURCE --get-volume)
    echo "$volume"
}

# Get icons
get_icon() {
    current=$(get_volume)
    isMuted=$(pamixer --source $SOURCE --get-mute)
    if [[ "$current" -eq "0" || $isMuted == true ]]; then
        echo "$iDIR/microphone-mute.png"
    else
        echo "$iDIR/microphone.png"
    fi
}

# Notify
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Microphone : $(get_volume)"
}

# Increase Volume
inc_volume() {
    pamixer --source $SOURCE -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer --source $SOURCE -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
    if [ "$(pamixer --source $SOURCE --get-mute)" == "false" ]; then
        pamixer -m --source $SOURCE && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
    elif [ "$(pamixer --source $SOURCE --get-mute)" == "true" ]; then
        pamixer -u --source $SOURCE && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
    fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--get-icon" ]]; then
    get_icon
else
    get_volume
fi
