#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get Volume
get_volume() {
    volume=$(pamixer --get-volume)
    echo "$volume"
}

# Get icons
get_icon() {
    current=$(get_volume)
    isMuted=$(pamixer --get-mute)
    if [[ "$current" -eq "0" || $isMuted == true ]]; then
        echo "$iDIR/volume-mute.png"
    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        echo "$iDIR/volume-low.png"
    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        echo "$iDIR/volume-mid.png"
        # elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
    else
        echo "$iDIR/volume-high.png"
    fi
}

# Notify
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume)"
}

# Increase Volume
inc_volume() {
    pamixer --allow-boost -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer --allow-boost -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
    if [ "$(pamixer --get-mute)" == "false" ]; then
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
    elif [ "$(pamixer --get-mute)" == "true" ]; then
        pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
    fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--get-icon" ]]; then
    get_icon
else
    get_volume
fi
