#!/bin/bash

CONFIG="$HOME/.config/hypr/wofifull/config"
STYLE="$HOME/.config/hypr/wofifull/style.css"
COLORS="$HOME/.config/hypr/wofifull/colors"

FULL_PATH=~

while [[ true ]]; do
    FILE=$(ls $FULL_PATH | wofi --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS})
    FULL_PATH+=/$FILE

    # if [[ -d $FULL_PATH ]]; then
    #     echo "$FULL_PATH is a directory"
    if [[ -f $FULL_PATH ]]; then
        FILE_EXTENSION=${FULL_PATH##*.}
        if [[ $FILE_EXTENSION == pdf ]]; then
            zathura $FULL_PATH
        fi
        break
        # else
        #     echo "$PASSED is not valid"
        #     exit 1
    fi
done
