#!/bin/bash

export EDITOR='nvim'
export VISUAL='nvim'
# export MANPAGER='nvim +Man!'
export PAGER='nvimpager'
export MANPAGER='nvimpager'

alias ls='exa --git --icons'
alias la='ls -a'
alias ll='ls -al'
alias l='ls'

alias v='nvim'

alias clean-packages="pacman -Scc && yay -Scc"
alias start-kvm="virsh net-start default"
#alias list-packages-size="expac "%n %m" | sort -gk2 | awk '{sum+=$2; printf "%-30s%20.2f MiB\n", $1, $2/2^20} END {printf "----------\n%-30s%20.2f GiB\n", "Total:", sum/2^30}'"
alias get-drives="sudo parted -l"
alias mic-listen="pacmd load-module module-loopback"
alias mic-unlisten="pacmd unload-module module-loopback"
alias pc="unset HISTFILE && sudo protonvpn c"
alias pd="unset HISTFILE && sudo protonvpn d"
alias uh="unset HISTFILE"
alias dust="dust -X hdd"

# mirror-video
# ffmpeg -i "$1" -vf hflip -c:a copy "$1-mirrored.mp4"

gra ()
{
    git remote add origin git@github.com:ranamashood/$1.git
}

list-packages-size() {
    expac "%n %m" | sort -gk2 | awk '{sum+=$2; printf "%-30s%20.2f MiB\n", $1, $2/2^20} END {printf "----------\n%-30s%20.2f GiB\n", "Total:", sum/2^30}'
}
list-packages-date() {
    expac --timefmt='%F %T' '%l %n' | sort -n
}

# PATH+=':$HOME/.scripts:$HOME/hdd/.npm-global/bin'
PATH+=":$HOME/.scripts"
export NPM_CONFIG_PREFIX="$HOME/.npm-global"
PATH+=":$HOME/flutter/bin"
PATH="$HOME/bin:$PATH"
PATH+=":~/.config/emacs/bin/"

# aliasing files/directories by reading alias-directories
while read -r line
do
    words=($line)
    alias ${words[0]}=${words[1]}
done < ~/.scripts/alias-directories

# path=~/university/sem-5/

# if [[ ! -d $path ]]; then
#     echo "dir doesn't exist"
# fi

eval "$(starship init bash)"
source /usr/share/autojump/autojump.bash

PATH="/home/mashood/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/mashood/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/mashood/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/mashood/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/mashood/perl5"; export PERL_MM_OPT;

fastfetch
