#!/bin/bash

export EDITOR='lvim'
export VISUAL='lvim'
# to be fixed
# export PAGER='lvim -R'
# export MANPAGER="lvim -c 'set ft=man' -"

alias ls='exa --git --icons'
alias la='ls -a'
alias ll='ls -al'
alias l='ls'

alias clean-packages="pacman -Scc && yay -Scc"
alias start-kvm="virsh net-start default"
#alias list-packages-size="expac "%n %m" | sort -gk2 | awk '{sum+=$2; printf "%-30s%20.2f MiB\n", $1, $2/2^20} END {printf "----------\n%-30s%20.2f GiB\n", "Total:", sum/2^30}'"
alias get-drives="sudo parted -l"
alias mic-listen="pacmd load-module module-loopback"
alias mic-unlisten="pacmd unload-module module-loopback"
alias pc="unset HISTFILE && sudo protonvpn c"
alias pd="unset HISTFILE && sudo protonvpn d"
alias uh="unset HISTFILE"

gra ()
{
    git remote add origin git@github.com:ranamashood/$1.git
}

list-packages-size() {
    expac "%n %m" | sort -gk2 | awk '{sum+=$2; printf "%-30s%20.2f MiB\n", $1, $2/2^20} END {printf "----------\n%-30s%20.2f GiB\n", "Total:", sum/2^30}'
}
list-packages-date() {
    expac --timefmt='%F %T' '%l %n' | sort -n
}

# PATH+=':$HOME/.scripts:$HOME/hdd/.npm-global/bin'
PATH+=":$HOME/.scripts"
export NPM_CONFIG_PREFIX="$HOME/.npm-global"
PATH+=":$HOME/flutter/bin"
PATH="$HOME/bin:$PATH"
PATH+=":~/.emacs.d/bin"

# aliasing files/directories by reading alias-directories
while read -r line
do
    words=($line)
    alias ${words[0]}=${words[1]}
done < ~/.scripts/alias-directories

# path=~/university/sem-5/

# if [[ ! -d $path ]]; then
#     echo "dir doesn't exist"
# fi

launch ()
{
    $HOME/.config/hypr/scripts/$1 & disown
}

wal-tile() {
    wal -n -i "$@"
    swww img "$(< "${HOME}/.cache/wal/wal")" --transition-step 2 --transition-fps 60 --transition-type center
    launch statusbar
    launch notifications
}

wal-theme() {
    wal -n --theme "$@"
    launch statusbar
    launch notifications
}

eval "$(starship init bash)"
source /usr/share/autojump/autojump.bash

fastfetch
