#!/bin/bash

echo -n "RAM usage: "
free -h | awk 'FNR == 2 { print $3 }'

echo -n "Uptime: "
uptime | awk '{ print $3 }' | sed -e "s/:/ hours, /;s/\(.*\),/\1 mins/"

echo -n "CPU temps: "
echo $(cat /sys/class/thermal/thermal_zone1/temp) / 1000 | bc | xargs -r echo -n
echo -e "\u00B0C"
